name: "FedEx composite action eg"
description: "FedEx composite action eg steps are mentioned below"  # "description" should be lowercase

runs:
  using: 'composite'
  steps:
    - name: Download Test Results
      uses: actions/download-artifact@v4

    - name: ServiceNow DevOps Unit Test Results
      uses: ServiceNow/servicenow-devops-test-report@main
      with:
        # Devops Integration User Name
        devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
        # Devops Integration User Password
        devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
        # ServiceNow Instance Name
        instance-url: ${{ secrets.SN_INSTANCE_URL }}
        # Orchestration Tool Id
        tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
        # Job Name
        job-name: 'ServiceNow DevOps Unit Test Results'  # Should be same name as declared in 'name' clause of the current Stage
        # Github Context
        context-github: ${{ toJSON(github) }}
        # JUnit xml report file name with path
        xml-report-filename: testng.xml  # if only JUnit tests, use target/surefire-reports/testng-results.xml
                                                                          # if both JUnit & TestNG tests, use target/surefire-reports/testng-junit-results/testng-results.xml


    # - name: Build change request payload
    # id: build-change-payload
    # uses: Fedex/eai-3538069-pdsm/devops-changes@main
    
    # - name: Open Change
    # if: needs.compliance_ppm.outputs.skip-compliance != 'true' && steps.skip.outputs.skip-pdsm != 'true'
    # id: open_pdsm_change
    # uses: ServiceNow/servicenow-devops-change@v2.0.0
