
name: DevOps E2E Invoke composite action
on: 
    workflow_dispatch:
    workflow_call:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:           
            - uses: actions/checkout@v2

            - name: Do something
              run: echo pretend to do something

              # Use composite action
            - name: Using devops composite action e2e
              uses: kiranlakhani20/CompositeActionRepo@v1
              with:
                  devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
                  devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
                  instance-url: ${{ secrets.SN_INSTANCE_URL }}
                  tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
                  context-github: ${{ toJSON(github) }}
                  
              
          
