
name: DevOps E2E Invoke composite action
on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      devops-integration-user-name: 
        description: "The username for DevOps integration."
        required: true
        type: string
      devops-integration-user-password:
        description: "The pass for DevOps integration."
        required: true
        type: string
      instance-url:
        description: "The pass for DevOps integration."
        required: true
        type: string
      tool-id:
        description: "The pass for DevOps integration."
        required: true
        type: string    
      context-github:
        description: "The pass for DevOps integration."
        required: true
        type: string  
       

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:           
            - uses: actions/checkout@v2

            - name: Do something
              run: echo pretend to do something

              # Use composite action
            - name: call-composite-action-test
              uses: kiranlakhani20/CompositeActionRepo@v18
              with:
                  devops-integration-user-name: ${{ inputs.devops-integration-user-name }}
                  devops-integration-user-password: ${{ inputs.devops-integration-user-password }}
                  instance-url: ${{ inputs.instance-url }}
                  # job-name: 'call-composite-action-test / Test'
                  tool-id: ${{ inputs.tool-id }}
                  context-github: ${{ inputs.context-github }}
                  
              
          
