name: FedExCICDParentWorkflow

on:
  workflow_dispatch:
  workflow_call: 
    secrets:
        SN_INSTANCE_URL: 
          required: true

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
jobs:
  build:
    name: build
    uses: kiranlakhani20/test-devops/.github/workflows/build-gradle.yml@master

  static-analysis:
    needs: [build]
    uses: kiranlakhani20/test-devops/.github/workflows/static-analysis-gradle.yml@master

  service-tests:
    needs: [build]
    uses: kiranlakhani20/test-devops/.github/workflows/test-service.yml@master

  deployment-dev:
    needs: [static-analysis, service-tests]
    uses: kiranlakhani20/test-devops/.github/workflows/deployment-nonproduction.yml@master
      
  foss-requests:
    needs: [deployment-dev]
    if: github.ref != format('refs/heads/{0}', github.event.repository.default_branch)
    uses: kiranlakhani20/test-devops/.github/workflows/foss-requests.yml@master

  deployment-test:
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    needs: [static-analysis, service-tests]
    uses: kiranlakhani20/test-devops/.github/workflows/deployment-nonproduction.yml@master
  
  call-composite-action-test:
    needs: [deployment-test]
    uses: kiranlakhani20/test-devops/.github/workflows/devopse2eflow.yml@master
    with: 
      devops-integration-token: 'rJ007XjkYiZvI9LgkmvteoG3zYIihdHL'
      instance-url: 'https://kingkong.service-now.com/'
      tool-id: '5d83b2e1478f4a1029b8834c326d43a4'
      context-github: ${{ toJSON(github) }}

  acceptance-tests:
    needs: [call-composite-action-test]
    uses: kiranlakhani20/test-devops/.github/workflows/test-acceptance.yml@master

  sleep:
    needs: [acceptance-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run : sleep 15


  deployment-production:
    # This step *must* depend on `build` because the `unit-test-results` are used from that step.
    needs: [build, acceptance-tests, sleep]
    uses: kiranlakhani20/test-devops/.github/workflows/deployment-production.yml@master


  # call-devops-change:
  #   # needs: [call-composite-action-test]
  #   # needs: [deployment-production]
  #   uses: kiranlakhani20/test-devops/.github/workflows/ChangeFlow.yml@master
  #   with: 
  #     devops-integration-token: 'DcMHit2SKjru5axFCC54gngVgWy2cJiA'
  #     instance-url: 'https://avitokyo4.service-now.com/'
  #     tool-id: 'bad75aecc3fe42102893772ce00131ba'
  #     context-github: ${{ toJSON(github) }}

  # deploy:
  #   needs: build
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   steps:     
  #     - name: Custom Change
  #       uses: ServiceNow/servicenow-devops-change@v4.0.0
  #       with:
  #         devops-integration-token: 'DcMHit2SKjru5axFCC54gngVgWy2cJiA'
  #         instance-url: https://avitokyo4.service-now.com
  #         tool-id: 'bad75aecc3fe42102893772ce00131ba'
  #         context-github: ${{ toJSON(github) }}
  #         job-name: 'Deploy'
  #         change-request: '{"setCloseCode":"true","attributes":{"short_description":"Automated Software Deployment","description":"Automated Software Deployment.","assignment_group":"a715cd759f2002002920bde8132e7018"}}'
  #         interval: '100'
  #         timeout: '3600'

  


  
    

  


    
