name: FedExCICDParentWorkflow

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
jobs:
  build:
    name: build
    uses: kiranlakhani20/test-devops/.github/workflows/build-gradle.yml@master

  static-analysis:
    needs: [build]
    uses: kiranlakhani20/test-devops/.github/workflows/static-analysis-gradle.yml@master

  service-tests:
    needs: [build]
    uses: kiranlakhani20/test-devops/.github/workflows/test-service.yml@master

  deployment-dev:
    needs: [static-analysis, service-tests]
    uses: kiranlakhani20/test-devops/.github/workflows/deployment-nonproduction.yml@master

  foss-requests:
    needs: [deployment-dev]
    if: github.ref != format('refs/heads/{0}', github.event.repository.default_branch)
    uses: kiranlakhani20/test-devops/.github/workflows/foss-requests.yml@master

  deployment-test:
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    needs: [static-analysis, service-tests]
    uses: kiranlakhani20/test-devops/.github/workflows/deployment-nonproduction.yml@master

  acceptance-tests:
    needs: [deployment-test]
    uses: kiranlakhani20/test-devops/.github/workflows/test-acceptance.yml@master


  deployment-production:
    # This step *must* depend on `build` because the `unit-test-results` are used from that step.
    needs: [build, acceptance-tests]
    uses: kiranlakhani20/test-devops/.github/workflows/deployment-production.yml@master

  call-composite-action:
    needs: [deployment-production]
    uses: kiranlakhani20/test-devops/.github/workflows/devopse2eflow.yml@master
    with:
      devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
      devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
      instance-url: ${{ secrets.SN_INSTANCE_URL }}
      tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
      context-github: ${{ toJSON(github) }}


  
    

  


    
